// This file is generated by `pnpm run generate:some-script`

import { bindModule } from '../bind';
import type { LocalizedFakerCore } from '../fakerCore';
import { localizedFakerCore } from '../fakerCore';
import { fakerFirstName, firstNameFn } from './firstname';

/**
 * The functions of the person module.
 */
export const personFns = {
  firstName: firstNameFn,
};

/**
 * The person module.
 */
export type Person = Readonly<{
  /**
   * Returns a random first name.
   *
   * @alias faker.name.firstName
   * @alias fakerName.firstName
   *
   * @param sex The optional sex to use.
   * Can be either `'female'` or `'male'`.
   *
   * @example
   * fakerFirstName() // 'Antwan'
   * fakerFirstName('female') // 'Victoria'
   * fakerFirstName('male') // 'Tom'
   *
   * @since 8.0.0
   */
  firstName: typeof fakerFirstName;
}>;

/**
 * Creates a new person module that is bound to the given faker core.
 *
 * @param fakerCore The faker core to bind the module to.
 */
export function bindPersonModule(fakerCore: LocalizedFakerCore): Person {
  return bindModule<LocalizedFakerCore, Person>(fakerCore, personFns);
}

// Either
export const fakerPerson: Person = bindPersonModule(localizedFakerCore);
// Or
export const fakerPerson2: Person = { firstName: fakerFirstName };
