// This file is generated by `pnpm run generate:some-script`

import { bindModule } from '../bind';
import type { FakerCore } from '../fakerCore';
import { fakerCore } from '../fakerCore';
import { arrayElementFn, fakerArrayElement } from './arrayElement';

/**
 * The functions of the helpers module.
 */
export const helpersFns = {
  arrayElement: arrayElementFn,
};

/**
 * The helpers module.
 */
export type Helpers = {
  /**
   * Returns a random element from the given array.
   *
   * @template T The type of the entries to pick from.
   * @param values The array to pick the value from.
   *
   * @example
   * fakerArrayElement(['cat', 'dog', 'mouse']) // 'dog'
   *
   * @since 8.0.0
   */
  arrayElement: <T>(values: T[]) => T;
};

/**
 * Creates a new helpers module that is bound to the given faker instance.
 *
 * @param fakerCore The faker instance to bind the module to.
 */
export function bindHelpersModule(fakerCore: FakerCore): Helpers {
  return bindModule<Helpers>(fakerCore, helpersFns);
}

// Either
export const fakerHelpers: Helpers = bindHelpersModule(fakerCore);
// Or
export const fakerHelpers2: Helpers = { arrayElement: fakerArrayElement };
