name: Check Release PR

on:
  pull_request:
    branches:
      - chore/release/**

permissions:
  contents: read

jobs:
  check_release_pr:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout faker
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          path: faker

      - name: Checkout playground
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          repository: faker-js/playground
          path: playground

      - name: Install pnpm
        uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # v4.0.0

      - name: Set node version to 22
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install deps - faker
        run: |
          cd faker
          pnpm install
        env:
          CYPRESS_INSTALL_BINARY: 0

      - name: Install deps - playground
        run: |
          cd playground
          sed -i 's/overrides-for-release/overrides/g' package.json
          pnpm install

      - name: Build - faker
        run: |
          cd faker
          pnpm run build

      - name: Build - playground
        run: |
          cd playground
          pnpm run build

      - name: Test - playground
        run: |
          cd playground
          pnpm run test
